/** Compétences du bulletin préscolaire — UUIDs fixes pour le sync. */
export type PreschoolBulletinSeed = {
  id: string;
  name: string;
  section: string;
  preschool_eval: 'LEVEL' | 'FREQUENCY';
};

function id(n: number): string {
  return `b0a1e001-0000-4000-8000-${String(n).padStart(12, '0')}`;
}

function rows(
  section: string,
  evalMode: 'LEVEL' | 'FREQUENCY',
  names: string[],
  start: number,
): PreschoolBulletinSeed[] {
  return names.map((name, i) => ({
    id: id(start + i),
    name,
    section,
    preschool_eval: evalMode,
  }));
}

export const PRESCHOOL_BULLETIN_SUBJECTS: PreschoolBulletinSeed[] = [
  ...rows('Motricité globale', 'LEVEL', [
    'Court',
    'Court en changeant de direction',
    'Sauts à pieds joints',
    'Marche sur la pointe des pieds',
    'Marche sur les talons',
    'Augmente sa vitesse de marche',
    'Se tient sur un pied',
    'Marche sur une ligne',
    'Marche en équilibre',
    'Peut lancer un ballon',
    'Peut attraper une balle',
    'Aide à sauter',
    'Avance et recule sur un pied',
  ], 1),
  ...rows('Habiletés', 'LEVEL', [
    'Lecture',
    'Écriture',
    'Calcul',
    'Dessin',
  ], 20),
  ...rows('Développement du langage', 'FREQUENCY', [
    'Communique, s’exprime',
    'Comprend et exécute les consignes',
    'S’exprime de façon claire',
    'S’exprime en français',
    'Utilise un vocabulaire approprié',
    'Arrive à identifier des images',
    'Utilise la parole de manière à se faire comprendre',
    'Peut lire des phrases simples',
    'Invente des situations de langage',
  ], 30),
  ...rows('Participation en classe', 'FREQUENCY', [
    'S’intéresse aux travaux manuels',
    'Mélange correctement les peintures',
    'Participe au sport',
    'Suit la rythmique',
    'Participe aux leçons d’observation',
    'Sait comprendre une histoire',
    'S’intéresse aux livres et images',
    'Participe aux jeux éducatifs',
    'Participe aux jeux récréatifs',
  ], 50),
  ...rows('Mathématique et perception', 'LEVEL', [
    'Identifie les formes géométriques : rond, carré, triangle, ovale, rectangle, losange, trapèze',
    'Identifie et nomme les couleurs : rouge, jaune, orange, rose, blanc, mauve, marron, noir, violet',
    'Associe les chiffres à une quantité',
    'Reconnaît les chiffres 1 à 10',
    'Reconnaît les nombres',
    'Arrive à ranger, classer, trier sur un critère donné',
    'Identifie les lettres de l’alphabet',
    'Reconnaît son initiale dans un mot',
  ], 70),
  ...rows('Grandeurs', 'LEVEL', [
    'Grand – petit',
    'Long – court',
    'Froid – chaud',
    'Plus que – moins que',
    'Plus grand – plus petit',
    'Autant',
    'Vide – plein',
    'Avant – après',
    'Entre',
    'Loin – près',
    'Rugueux – lisse',
    'Épais – mince',
    'Identifie et nomme les différentes parties de son corps',
  ], 90),
  ...rows('Socialisation', 'FREQUENCY', [
    'Dit Bonjour',
    'Dit S’il vous plaît',
    'Dit Merci',
    'Dit Au revoir',
    'Est sociable',
    'Participe aux activités',
    'Attend son tour',
    'Apprend à écouter les autres',
    'Termine ses travaux',
    'Fait ses devoirs',
    'Sait organiser ses activités',
  ], 110),
  ...rows('Orientation spatiale', 'LEVEL', [
    'Sur – sous',
    'Devant – derrière',
    'En haut – en bas',
    'Gauche – droite',
    'Intérieur – extérieur',
    'En-dessous – au-dessus',
    'Dedans – dehors',
    'Dessus – dessous',
  ], 130),
  ...rows('English', 'LEVEL', [
    'Can speak clearly and correctly',
    'Recitation and repeat stories',
    'Rhyme verses and songs',
    'Know first and last name',
    'Can button',
    'Can zip',
    'Can tie a bow',
    'Can follow simple talk',
    'Follow directions',
    'Enjoy art activities',
    'Can write his/her name',
    'Can count objects',
    'Can recognize numbers',
    'Can write numbers',
    'Can recognize the letters of the alphabet',
    'Can recognize basic shapes',
    'Can draw basic shapes and lines',
    'Can recognize basic colors',
    'Know the parts of the body',
    'Can identify the fruits and vegetables',
    'Can identify animals',
    'Can identify familiar objects',
  ], 150),
  ...rows('Motricité fine', 'LEVEL', [
    'Contourne une forme',
    'Suit une ligne pointillée',
    'Maîtrise la tenue d’un crayon, un pinceau',
    'Attache les boutons',
    'Met les lacets',
    'Reconnaît l’endroit / l’envers',
    'Collage intérieur d’une forme',
    'Découpage',
    'Modelage',
    'Pliage',
    'Gribouillage, collage',
    'Tissage, découpage',
    'Broderie',
    'Reconnaît les lignes : droite (verticale, horizontale), courbe, brisée, oblique',
  ], 180),
  ...rows('Art', 'LEVEL', [
    'Peinture',
    'Collage',
    'Dessin libre',
    'Chant',
    'Danse',
  ], 200),
];
