import type { EducationLevelKey } from './education-levels';

/**
 * Une école peut renommer le rôle depuis « Gestion des rôles » (TEACHER →
 * PROFESSEUR). Les comptes gardent le même role_id : reconnaître les alias
 * évite un annuaire professeurs vide.
 */
export const TEACHER_ROLE_NAMES = [
  'TEACHER',
  'PROFESSEUR',
  'PROFESSEURE',
  'PROF',
  'ENSEIGNANT',
  'ENSEIGNANTE',
];

export function isTeacherRoleName(name?: string | null): boolean {
  return TEACHER_ROLE_NAMES.includes((name ?? '').toUpperCase().trim());
}

export const ROLE_NAMES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DIRECTEUR_GENERAL: 'DIRECTEUR_GENERAL',
  DIRECTEUR_ADMINISTRATIF: 'DIRECTEUR_ADMINISTRATIF',
  ADMINISTRATEUR: 'ADMINISTRATEUR',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  DIRECTEUR_PEDAGOGIQUE: 'DIRECTEUR_PEDAGOGIQUE',
  DIRECTEUR_PEDAGOGIQUE_PRESCOLAIRE: 'DIRECTEUR_PEDAGOGIQUE_PRESCOLAIRE',
  DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL: 'DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL',
  DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_2: 'DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_2',
  DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_3: 'DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_3',
  DIRECTEUR_PEDAGOGIQUE_SECONDAIRE: 'DIRECTEUR_PEDAGOGIQUE_SECONDAIRE',
  DIRECTEUR_PEDAGOGIQUE_FORMATION_SUPERIEURE:
    'DIRECTEUR_PEDAGOGIQUE_FORMATION_SUPERIEURE',
  CENSEUR: 'CENSEUR',
  ADMIN_PRESCOLAIRE: 'ADMIN_PRESCOLAIRE',
  ADMIN_FONDAMENTAL: 'ADMIN_FONDAMENTAL',
  ADMIN_SECONDAIRE: 'ADMIN_SECONDAIRE',
  SECRETAIRE_GENERAL: 'SECRETAIRE_GENERAL',
  SECRETAIRE_FORMATION_SUPERIEURE: 'SECRETAIRE_FORMATION_SUPERIEURE',
  SURVEILLANT_GENERAL: 'SURVEILLANT_GENERAL',
  ECONOME: 'ECONOME',
  COMPTABLE: 'COMPTABLE',
  DISCIPLINE: 'DISCIPLINE',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STAFF: 'STAFF',
} as const;

/** Direction / administration : accès à tout, tous les niveaux. */
export const ROLES_FULL_SCHOOL = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.DIRECTEUR_ADMINISTRATIF,
  ROLE_NAMES.ADMINISTRATEUR,
  ROLE_NAMES.SCHOOL_ADMIN,
];

export function isFullAccessRoleName(name?: string | null): boolean {
  return (ROLES_FULL_SCHOOL as readonly string[]).includes(
    (name ?? '').toUpperCase().trim(),
  );
}

export const ROLES_PEDAGOGIQUE = [
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_PRESCOLAIRE,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_2,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_3,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_SECONDAIRE,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE_FORMATION_SUPERIEURE,
  ROLE_NAMES.ADMIN_PRESCOLAIRE,
  ROLE_NAMES.ADMIN_FONDAMENTAL,
  ROLE_NAMES.ADMIN_SECONDAIRE,
  ROLE_NAMES.CENSEUR,
];

export const ROLES_SECRETAIRE = [
  ROLE_NAMES.SECRETAIRE_GENERAL,
  ROLE_NAMES.SECRETAIRE_FORMATION_SUPERIEURE,
];

export const ROLES_SURVEILLANT = [
  ROLE_NAMES.SURVEILLANT_GENERAL,
  ROLE_NAMES.DISCIPLINE,
];

export const PERMS_PEDAGOGIQUE = [
  'grades',
  'schedule',
  'stats-academiques',
  'fiche-eleve',
  'formation-classe',
  'students',
  'classes',
];

export const PERMS_SECRETAIRE = ['students', 'fiche-eleve', 'classes'];

export const PERMS_SURVEILLANT = ['discipline'];

/** Niveaux par défaut d’un rôle — `null` = toute l’école. */
export const DEFAULT_ROLE_EDUCATION_LEVELS: Record<string, EducationLevelKey[] | null> =
  {
    SUPER_ADMIN: null,
    DIRECTEUR_GENERAL: null,
    DIRECTEUR_ADMINISTRATIF: null,
    ADMINISTRATEUR: null,
    SCHOOL_ADMIN: null,
    DIRECTEUR_PEDAGOGIQUE: null,
    DIRECTEUR_PEDAGOGIQUE_PRESCOLAIRE: ['PRESCOLAIRE'],
    ADMIN_PRESCOLAIRE: ['PRESCOLAIRE'],
    DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL: ['FONDAMENTAL_1', 'FONDAMENTAL_2'],
    ADMIN_FONDAMENTAL: ['FONDAMENTAL_1', 'FONDAMENTAL_2'],
    DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_2: ['FONDAMENTAL_2'],
    DIRECTEUR_PEDAGOGIQUE_FONDAMENTAL_3: ['FONDAMENTAL_3'],
    DIRECTEUR_PEDAGOGIQUE_SECONDAIRE: ['SECONDAIRE'],
    ADMIN_SECONDAIRE: ['SECONDAIRE'],
    DIRECTEUR_PEDAGOGIQUE_FORMATION_SUPERIEURE: ['FORMATION_SUPERIEURE'],
    SECRETAIRE_GENERAL: null,
    SECRETAIRE_FORMATION_SUPERIEURE: ['FORMATION_SUPERIEURE'],
    CENSEUR: null,
    SURVEILLANT_GENERAL: null,
    DISCIPLINE: null,
    ECONOME: null,
    COMPTABLE: null,
    TEACHER: null,
    PARENT: null,
  };

export const ROLES_ECONOMAT_FULL = [
  ...ROLES_FULL_SCHOOL,
  ...ROLES_PEDAGOGIQUE,
  ROLE_NAMES.STAFF,
];

export const ROLES_ECONOMAT_PAYMENTS_ONLY = [
  ...ROLES_ECONOMAT_FULL,
  ROLE_NAMES.ECONOME,
];

export const ROLES_SCHOOL_MANAGEMENT = [
  ...ROLES_FULL_SCHOOL,
  ...ROLES_PEDAGOGIQUE,
  ...ROLES_SECRETAIRE,
  ROLE_NAMES.STAFF,
];

export const ROLES_GRADES = [
  ...ROLES_FULL_SCHOOL,
  ...ROLES_PEDAGOGIQUE,
  ROLE_NAMES.STAFF,
  ...TEACHER_ROLE_NAMES,
];

export const ROLES_USER_ADMIN = [...ROLES_FULL_SCHOOL];
