export const ROLE_NAMES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DIRECTEUR_GENERAL: 'DIRECTEUR_GENERAL',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  DIRECTEUR_PEDAGOGIQUE: 'DIRECTEUR_PEDAGOGIQUE',
  CENSEUR: 'CENSEUR',
  ADMIN_PRESCOLAIRE: 'ADMIN_PRESCOLAIRE',
  ADMIN_FONDAMENTAL: 'ADMIN_FONDAMENTAL',
  ADMIN_SECONDAIRE: 'ADMIN_SECONDAIRE',
  ECONOME: 'ECONOME',
  DISCIPLINE: 'DISCIPLINE',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  STAFF: 'STAFF',
} as const;

export const ROLES_FULL_SCHOOL = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.SCHOOL_ADMIN,
];

export const ROLES_ECONOMAT_FULL = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.SCHOOL_ADMIN,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE,
  ROLE_NAMES.CENSEUR,
  ROLE_NAMES.ADMIN_PRESCOLAIRE,
  ROLE_NAMES.ADMIN_FONDAMENTAL,
  ROLE_NAMES.ADMIN_SECONDAIRE,
  ROLE_NAMES.STAFF,
];

export const ROLES_ECONOMAT_PAYMENTS_ONLY = [
  ...ROLES_ECONOMAT_FULL,
  ROLE_NAMES.ECONOME,
];

export const ROLES_SCHOOL_MANAGEMENT = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.SCHOOL_ADMIN,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE,
  ROLE_NAMES.CENSEUR,
  ROLE_NAMES.ADMIN_PRESCOLAIRE,
  ROLE_NAMES.ADMIN_FONDAMENTAL,
  ROLE_NAMES.ADMIN_SECONDAIRE,
  ROLE_NAMES.STAFF,
];

export const ROLES_GRADES = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.SCHOOL_ADMIN,
  ROLE_NAMES.DIRECTEUR_PEDAGOGIQUE,
  ROLE_NAMES.CENSEUR,
  ROLE_NAMES.ADMIN_PRESCOLAIRE,
  ROLE_NAMES.ADMIN_FONDAMENTAL,
  ROLE_NAMES.ADMIN_SECONDAIRE,
  ROLE_NAMES.STAFF,
  ROLE_NAMES.TEACHER,
];

export const ROLES_USER_ADMIN = [
  ROLE_NAMES.SUPER_ADMIN,
  ROLE_NAMES.DIRECTEUR_GENERAL,
  ROLE_NAMES.SCHOOL_ADMIN,
];
