/** Ordre sync (doit matcher le backend SYNC_ENTITY_DEFS).
 * SyncTombstone EN PREMIER : propager les deletes plus récents
 * avant les upserts du même cycle (anti-rebond). LWW vs ligne vivante.
 */
export const ENTITY_ORDER = [
  'SyncTombstone',
  'SchoolProfile',
  'SchoolSignature',
  'User',
  'AcademicYear',
  'Period',
  'Subject',
  'Class',
  'Room',
  'ClassSubject',
  'Student',
  'UserLinkedStudent',
  'StudentParent',
  'StudentPhoto',
  'FeeService',
  'ClassFee',
  'ClassSubjectCoefficient',
  'ExamSchedule',
  'ScheduleSlot',
  'ExtracurricularActivity',
  'StudentClassAssignment',
  'ClassDecisionThreshold',
  'Grade',
  'PreschoolGrade',
  'Bank',
  'BankAccount',
  'Expense',
  'FileMetadata',
  'Attendance',
  'PaymentTransaction',
];
